### PR TITLE
Add RFAA and HF3 modules

### PR DESCRIPTION
**Pull request by jscgh**
- Combines the add-rosettafold-all-atom and add-helixfold3 branches
- Merged with [nf-core/dev](https://github.com/nf-core/proteinfold/tree/dev)

## PR checklist

- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,**singularity** --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,**singularity** --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nbtm-sh** [comment]
Will run tests through OnDemand later today. Keep you posted!

**Comment by nbtm-sh** [comment]
Running HF3 I get this output:
[output.log](https://github.com/user-attachments/files/18017162/output.log)

**Comment by jscgh** [comment]
Seems to be from `Message: "Could not open file: ./maxit_src/data/binary/variant.odb" generated at: BlockIO::OpenFile`

Permissions error on the DBs.
`-rw-------. 1 z5378336 sbf 1.9M Sep 10 16:18 variant.odb`
Should be fixed now.

**Comment by nbtm-sh** [comment]
Tests completed fine. Looks good to me

**Review by nbtm-sh — APPROVED** [review]

**Pull request merged**
